%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kbutler/Documents/MATLAB/Joint Causation/for publication/data/real+estate+valuation+data+set/Real estate valuation data set.xlsx
%    Worksheet: 工作表1
%
% Auto-generated by MATLAB on 17-Nov-2023 11:59:16

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "工作表1";
opts.DataRange = "A2:H415";

% Specify column names and types
opts.VariableNames = ["No", "X1TransactionDate", "X2HouseAge", "X3DistanceToTheNearestMRTStation", "X4NumberOfConvenienceStores", "X5Latitude", "X6Longitude", "YHousePriceOfUnitArea"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Realestatevaluationdataset = readtable("./data/real+estate+valuation+data+set/Real estate valuation data set.xlsx", opts, "UseExcel", false);

% Convert to output type
Realestatevaluationdataset = table2array(Realestatevaluationdataset);

% Clear temporary variables
clear opts


Realestatevaluationdataset = Realestatevaluationdataset(randperm(414)',:);